[project]
version = "0.0.1"

[logging]
level = "debug"
format = '%(asctime)s | %(name)s | %(levelname)s | %(message)s'

[json_report]
# example: "./test/index.json"
#input_file_path = './index.json'
input_file_path = '/Users/hugofernandes/projects/corporate/portal-automation/cypress/reports/html/index.json'

write_stats_file = false
output_file_path = './stats.json'

[mysql]
host = "localhost"
port = "3306"
username = "root"
# the program tries to search for env variable first as GRAFANA_MYSQL_PASS of not defined uses the one here
password = "password"
[mysql.datasource]
db_name = "grafana"
db_table = "mochawesome"
