{
 "title": "Mochawesome Test Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Latest Run", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Test Execution Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT \n  tests_nr as 'number of tests', \n  passes as 'passed tests', \n  pending as 'pending tests',\n  skipped as 'skipped tests',\n  failures as 'failed tests'\nFROM \n  grafana.mochawesome \nORDER BY \n  create_datetime desc \nLIMIT \n  1"
    }
   ]
  },
  {
   "title": "Execution Time in Seconds",
   "type": "stat",
   "description": "Provides the latest execution time in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT duration_ms/1000 FROM grafana.mochawesome ORDER BY create_datetime desc LIMIT 1 "
    }
   ]
  },
  {
   "title": "Execution Statistics - Last 10 Runs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Min Exec Time in Secs - Any Nr of Tests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT \n  MIN(duration_ms / 1000) \nFROM \n  (\n    SELECT \n      duration_ms \n    FROM \n      grafana.mochawesome \n    ORDER BY \n      create_datetime DESC \n    LIMIT \n      10\n  ) tbl"
    }
   ]
  },
  {
   "title": "Min Exec Time in Secs - All Tests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT \n  MIN(duration_ms / 1000) \nFROM \n  (\n    SELECT \n      duration_ms \n    FROM \n      grafana.mochawesome \n    WHERE \n      tests_nr = (\n        SELECT \n          MAX(tests_nr) \n        FROM \n          grafana.mochawesome\n      ) \n    ORDER BY \n      create_datetime DESC \n    LIMIT \n      10\n  ) tbl"
    }
   ]
  },
  {
   "title": "Avg Pass Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT \n  CASE \n    WHEN ROUND(AVG(tbl.pass_percent), 1) = 99.9 THEN 100 \n    ELSE ROUND(AVG(tbl.pass_percent),1) \n  END \nFROM \n  (Select pass_percent from grafana.mochawesome ORDER BY \n  create_datetime desc \nLIMIT \n  10) tbl\n\n"
    }
   ]
  },
  {
   "title": "Last 10 Runs Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT create_datetime, tests_nr, passes, failures, pending, skipped FROM grafana.mochawesome ORDER BY create_datetime DESC LIMIT 10 "
    }
   ]
  },
  {
   "title": "Avg Exec Time in Secs - Any Nr of Tests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT \n  AVG(duration_ms / 1000) \nFROM \n  (\n    SELECT \n      duration_ms \n    FROM \n      grafana.mochawesome \n    ORDER BY \n      create_datetime DESC \n    LIMIT \n      10\n  ) tbl"
    }
   ]
  },
  {
   "title": "Avg Exec Time in Secs - All Tests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT \n  AVG(duration_ms / 1000) \nFROM \n  (\n    SELECT \n      duration_ms \n    FROM \n      grafana.mochawesome \n    WHERE \n      tests_nr = (\n        SELECT \n          MAX(tests_nr) \n        FROM \n          grafana.mochawesome\n      ) \n    ORDER BY \n      create_datetime DESC \n    LIMIT \n      10\n  ) tbl"
    }
   ]
  },
  {
   "title": "Max  Failed Tests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT \nMAX(failures)\nFROM \n  (Select failures from grafana.mochawesome ORDER BY \n  create_datetime desc \nLIMIT \n  10) tbl\n\n"
    }
   ]
  },
  {
   "title": "Max Exec Time in Secs - Any Nr of Tests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT \n  MAX(duration_ms / 1000) \nFROM \n  (\n    SELECT \n      duration_ms \n    FROM \n      grafana.mochawesome \n    ORDER BY \n      create_datetime DESC \n    LIMIT \n      10\n  ) tbl"
    }
   ]
  },
  {
   "title": "Max Exec Time in Secs - All Tests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT \n  MAX(duration_ms / 1000) \nFROM \n  (\n    SELECT \n      duration_ms \n    FROM \n      grafana.mochawesome \n    WHERE \n      tests_nr = (\n        SELECT \n          MAX(tests_nr) \n        FROM \n          grafana.mochawesome\n      ) \n    ORDER BY \n      create_datetime DESC \n    LIMIT \n      10\n  ) tbl"
    }
   ]
  },
  { "title": "Executions History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Executions Time in seconds",
   "type": "timeseries",
   "description": "Displays the test execution times",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT duration_ms/1000 as 'duration in seconds', create_datetime FROM grafana.mochawesome LIMIT 500 "
    }
   ]
  },
  {
   "title": "Avg Pass Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT \n  CASE \n    WHEN ROUND(AVG(pass_percent), 1) = 99.9 THEN 100 \n    ELSE ROUND(AVG(pass_percent),1) \n  END \nFROM \n  grafana.mochawesome \nORDER BY \n  create_datetime desc\n"
    }
   ]
  }
 ]
}